title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: |
  <p align="center">
  <a href="https://github.com/TJGO-JDD">GIT HUB TJGO</a> 
  </p>
  
  <p align="justify">
    Bachiller de la Universidad Nacional de San Cristóbal de Huamanga, interesado en la automatización y programación aplicada a la ingeniería civil. Su enfoque principal está en la interoperabilidad de programas y la implementación de soluciones tecnológicas para optimizar los procesos en proyectos de ingeniería, buscando siempre mejorar la eficiencia y obtener mejores resultados mediante la automatización de tareas y el uso de herramientas avanzadas.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
