title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: >
  Bachiller de la Universidad Nacional de San Cristóbal de Huamanga, interesado en la automatización y programación aplicada a la ingeniería civil.

remote_theme: mmistakes/minimal-mistakes@4.24.0  # <== Aquí está el cambio
plugins:
  - jekyll-remote-theme

google_analytics: G-ZZYG0XLBM7

markdown: kramdown
kramdown:
  math_engine: mathjax
