title: "ÑOL IVAN JUAN DE DIOS ROJAS"
logo: /assets/img/PERFIL.JPG

description: |
 
  <p align="justify">
    Ingeniero Civil en formación por la Universidad Nacional de San Cristóbal de Huamanga, enfocado en automatización y programación aplicada a la ingeniería civil. Especializado en interoperabilidad de software y desarrollo de herramientas tecnológicas para optimizar procesos en proyectos de ingeniería. Creador de software de escritorio orientado a la automatización de tareas técnicas, integrando análisis estructural, procesamiento de datos y flujos de trabajo computacionales para mejorar la eficiencia y precisión en proyectos de ingeniería.
  </p>

google_analytics: G-ZZYG0XLBM7

theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
